version: "0.0.1"

x-common-variables: &common-variables
  MYSQL_USER: shortener
  MYSQL_PASSWORD: T5fgZ4L66n7z
  MYSQL_DATABASE: shortener
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mariadb:latest
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/shortener.sql:/docker-entrypoint-initdb.d/shortener.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8089:80
    restart: always
  server:
    build: ./server
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8001:8000
    volumes:
      - ./server:/app
    links:
      - mysql-db
    command: npm start
  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3009:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start